### ISSUE TITLE
Timeout in register scan

### ISSUE THREAD

**Issue by austinmroczek** [jmccrohan/pysolarmanv5#13]
Per discord discussion, I'm not sure my device is ever going to respond...but register_scan.py does not catch timeout error.  So somewhere in the middle of the 10,000 address scan it stopped.  Would be nice to catch this and retry, or at least tell user what the last address scanned was.

```txt
Traceback (most recent call last):
  File "C:\Users\Admin\git\pysolarmanv5\examples\register_scan.py", line 27, in <module>
    main()
  File "C:\Users\Admin\git\pysolarmanv5\examples\register_scan.py", line 11, in main
    val = modbus.read_input_registers(register_addr=x, quantity=1)[0]
  File "C:\Python310\lib\site-packages\pysolarmanv5\pysolarmanv5.py", line 224, in read_input_registers
    modbus_values = self._get_modbus_response(mb_request_frame)
  File "C:\Python310\lib\site-packages\pysolarmanv5\pysolarmanv5.py", line 178, in _get_modbus_response
    mb_response_frame = self._send_receive_modbus_frame(mb_request_frame)
  File "C:\Python310\lib\site-packages\pysolarmanv5\pysolarmanv5.py", line 172, in _send_receive_modbus_frame
    v5_response_frame = self._send_receive_v5_frame(v5_request_frame)
  File "C:\Python310\lib\site-packages\pysolarmanv5\pysolarmanv5.py", line 163, in _send_receive_v5_frame
    v5_response = self.sock.recv(1024)
TimeoutError: timed out
```

**Comment by austinmroczek** [comment]
My device uses a similar but different scheme.  You could try my code at https://github.com/austinmroczek/modbus_mapper
