### ISSUE TITLE
Unknown errors

### ISSUE THREAD

**Issue by torsteinelv** [jmccrohan/pysolarmanv5#40]
Hello,

Been testing this project for a while just changing 2 values on a deye inverter and it works very well.

Just have some questions on some error messages that i receave from time to time if someone can correct me and help me understand why they come:
`ERROR:__main__:An error occurred: V5 frame contains invalid sequence number
2023-06-01 21:06:56,640 - __main__ - ERROR - An error occurred: V5 frame contains invalid sequence number
Exception in thread Thread-28 (_data_receiver):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/site-packages/pysolarmanv5/pysolarmanv5.py", line 313, in _data_receiver
    self._data_queue.put(data, timeout=self.socket_timeout)
  File "/usr/lib/python3.11/multiprocessing/queues.py", line 90, in put
    raise Full
queue.Full
2023-06-02 07:12:16,256 - __main__ - ERROR - An error occurred: No socket available
ERROR:__main__:An error occurred: No socket available
2023-06-02 07:13:16,296 - __main__ - INFO - State changed! New state: 30.0
INFO:__main__:State changed! New state: 30.0
2023-06-02 07:13:16,298 - __main__ - ERROR - An error occurred: No socket available
ERROR:__main__:An error occurred: No socket available
INFO:__main__:State changed! New state: 30.0
2023-06-02 07:14:16,349 - __main__ - INFO - State changed! New state: 30.0
2023-06-02 07:14:16,351 - __main__ - ERROR - An error occurred: No socket available
ERROR:__main__:An error occurred: No socket available
2023-06-02 07:15:16,399 - __main__ - INFO - State changed! New state: 30.0
INFO:__main__:State changed! New state: 30.0
2023-06-02 07:15:16,402 - __main__ - ERROR - An error occurred: No socket available
ERROR:__main__:An error occurred: No socket available
2023-06-02 07:16:16,463 - __main__ - INFO - State changed! New state: 30.0
INFO:__main__:State changed! New state: 30.0
2023-06-02 07:16:19,521 - __main__ - ERROR - An error occurred: No socket available
ERROR:__main__:An error occurred: No socket available
2023-06-02 07:17:19,558 - __main__ - INFO - State changed! New state: 30.0
INFO:__main__:State changed! New state: 30.0
2023-06-02 07:17:22,624 - __main__ - ERROR - An error occurred: No socket available
ERROR:__main__:An error occurred: No socket available
INFO:__main__:State changed! New state: 30.0
2023-06-02 07:18:22,662 - __main__ - INFO - State changed! New state: 30.0
ERROR:__main__:An error occurred: No socket available
2023-06-02 07:18:54,592 - __main__ - ERROR - An error occurred: No socket available
2023-06-02 07:19:54,643 - __main__ - INFO - State changed! New state: 30.0
INFO:__main__:State changed! New state: 30.0
2023-06-02 07:20:26,240 - __main__ - ERROR - An error occurred: No socket available
ERROR:__main__:An error occurred: No socket available
INFO:__main__:State changed! New state: 30.0
2023-06-02 07:21:27,657 - __main__ - INFO - State changed! New state: 30.0
2023-06-02 07:21:59,424 - __main__ - ERROR - An error occurred: No socket available
ERROR:__main__:An error occurred: No socket available
2023-06-02 07:22:59,494 - __main__ - INFO - State changed! New state: 30.0
INFO:__main__:State changed! New state: 30.0
ERROR:__main__:An error occurred: No socket available
2023-06-02 07:23:31,076 - __main__ - ERROR - An error occurred: No socket available
2023-06-02 07:24:31,141 - __main__ - INFO - State changed! New state: 30.0
INFO:__main__:State changed! New state: 30.0`

**Comment by jmccrohan** [comment]
I'm going to close this. Please raise a new issue if you are able to recreate on the latest version.
